---
- hosts: all
  tasks:

#  - name: Copy file with owner and permissions
#    ansible.builtin.copy:
#      src: /tmp/zabbix-release-4.0-1.el7.noarch.rpm
#      dest: /tmp
#      owner: foo
#      group: foo
#      mode: '0644'

  - name: Install remote
    yum:
#      name: /tmp/zabbix-release-4.0-1.el7.noarch.rpm
       name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
       state: present
       disable_gpg_check: True
    
  - name: Install the zabbix-agent
    yum:
      name: zabbix-agent
      state: present
    
  - name: Enabling service
    systemd:
      name: zabbix-agent
      enabled: yes

  - name: Start service
    systemd:
      state: started
      name: zabbix-agent
     
